# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Test
      id: test
      needs: [setup-go]
      run: go test -v ./... -race

    - name: Build
      id: build
      needs: [setup-go, test]
      run: |
        CGO_ENABLED=0 GOOS=darwin go build -v ./...
        CGO_ENABLED=0 GOOS=linux go build -v ./...
        CGO_ENABLED=0 GOOS=windows go build -v ./...
